version: '3'
services:
  django:  &django
    environment:
      - DEBUG=True
    restart: on-failure
    build: 
      context: .
      dockerfile: ./docker/dev/django/Dockerfile
    command: >
                sh -c "
                python manage.py migrate &&
                python manage.py check_deploy_scripts &&
                python manage.py runserver 0.0.0.0:8000
                "
    volumes:
    - .:/code
    ports:
    - 8000:8000
    - 3000:3000