from .usuario_viewset import UsuarioViewset
from .categoria_viewset import CategoriaViewset
from .clube_viewset import ClubeViewset
from .combinacao_viewset import CombinacaoViewset
from .competicao_viewset import CompeticaoViewset
from .equipe_atleta_viewset import EquipeAtletaViewset
from .estado_viewset import EstadoViewset
from .equipe_viewset import EquipeViewset
from .cidade_viewset import CidadeViewset